# Generated by Django 4.2.6 on 2023-10-05 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AprendizFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('idFicha', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('centroSena', models.CharField(max_length=60)),
                ('dependenciaSena', models.CharField(max_length=50)),
                ('programaFormacion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorFicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idFichaFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaseg_app.ficha')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoDocumento', models.CharField(max_length=50)),
                ('siglasTipoDocumento', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='TipoProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTipoProceso', models.CharField(max_length=30)),
                ('descripcionTipoProceso', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('numeroDocumento', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('primerNombreUsuario', models.CharField(max_length=30)),
                ('segundoNombreUsuario', models.CharField(blank=True, max_length=30, null=True)),
                ('primerApellidoUsuario', models.CharField(max_length=40)),
                ('segundoApellidoUsuario', models.CharField(blank=True, max_length=40, null=True)),
                ('correoUsuario', models.CharField(max_length=60)),
                ('telefonoUsuario', models.CharField(max_length=10)),
                ('direccionUsuario', models.CharField(max_length=40)),
                ('idRolFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaseg_app.rol')),
                ('tipoDocumentoFK', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaseg_app.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaCreacionProceso', models.DateField()),
                ('causasProceso', models.TextField()),
                ('RutaEvidenciasProceso', models.TextField()),
                ('idAprendizFK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evaseg_app.aprendizficha')),
                ('idInstructorFK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evaseg_app.instructorficha')),
                ('tipoProcesoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaseg_app.tipoproceso')),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrasena', models.CharField(max_length=40)),
                ('numeroDocumentoFK', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evaseg_app.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='instructorficha',
            name='idInstructorFK',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaseg_app.usuario'),
        ),
        migrations.CreateModel(
            name='DetalleProceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHorainicioProceso', models.DateTimeField()),
                ('fechaHoraFinProceso', models.DateTimeField()),
                ('calificacionGravedadProceso', models.CharField(max_length=30)),
                ('decargosProceso', models.TextField()),
                ('rutaEvidenciasDescargosProceso', models.TextField()),
                ('detallesProceso', models.TextField()),
                ('decisionProceso', models.TextField()),
                ('idProcesoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaseg_app.proceso')),
            ],
        ),
        migrations.CreateModel(
            name='Citacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaHoraCitacion', models.DateTimeField()),
                ('idProcesoFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaseg_app.proceso')),
            ],
        ),
        migrations.AddField(
            model_name='aprendizficha',
            name='idAprendizFK',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaseg_app.usuario'),
        ),
        migrations.AddField(
            model_name='aprendizficha',
            name='idFichaFK',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='evaseg_app.ficha'),
        ),
    ]
