# Generated by Django 4.2.6 on 2023-10-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaseg_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rol',
            name='descripcionRol',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rol',
            name='tipoRol',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
